version: '3.8'
services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    init: true
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
